version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"  # Map port 8080 di host ke port 80 di container
    networks:
      - app-network
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge